name: Outputs workflow

on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      commit-sha: ${{ steps.commit.outputs.sha }}
      security-check: ${{ steps.security.outputs.passed }}
    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: npm ci

      - name: Generate version
        id: version
        run: |
          VERSION="1.2.3-${{ github.run_number }}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get commit SHA
        id: commit
        run: |
          SHA=$(git rev-parse --short HEAD)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Run security checks
        id: security
        run: |
          npm audit --audit-level=moderate
          echo "passed=true" >> $GITHUB_OUTPUT

      - run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy if security passed
        if: needs.build.outputs.security-check == 'true'
        run: |
          echo "Deploying version ${{ needs.build.outputs.version }}"
          echo "From commit ${{ needs.build.outputs.commit-sha }}"
          echo "Security checks: PASSED"
